package ai.shelter.shelterbackend.repository

import ai.shelter.shelterbackend.entity.Cat
import org.springframework.data.jpa.repository.JpaRepository

/* generated by ChatGPT */
interface CatRepository : JpaRepository<Cat, Long>