package ai.shelter.shelterbackend.repository

import ai.shelter.shelterbackend.entity.Location
import org.springframework.data.jpa.repository.JpaRepository

/* generated by ChatGPT */
interface LocationRepository : JpaRepository<Location, Long>