package ai.shelter.shelterbackend.entity

import javax.persistence.*

/* generated by ChatGPT */
@Entity
@Table(name = "cats")
data class Cat(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,

    @Column(nullable = false)
    var name: String,

    @ManyToOne
    @JoinColumn(name = "location_id", nullable = false)
    var location: Location
)